# Generated by Django 4.2.1 on 2023-12-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0049_caja_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='id_caja',
            new_name='empleado',
        ),
        migrations.AddField(
            model_name='caja',
            name='numero',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
