# Generated by Django 4.2.1 on 2023-12-18 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0053_factura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.proveedor'),
        ),
    ]
