# Generated by Django 4.2.1 on 2023-12-18 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0054_alter_factura_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='caja',
            name='turno',
            field=models.CharField(choices=[('Mañana', 'Mañana'), ('Tarde', 'Tarde')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
