# Generated by Django 4.2.1 on 2023-12-18 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0055_caja_turno'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caja',
            old_name='fecha_apertura',
            new_name='fecha_hora_apertura',
        ),
        migrations.RenameField(
            model_name='caja',
            old_name='fecha_cierre',
            new_name='fecha_hora_cierre',
        ),
        migrations.AddField(
            model_name='caja',
            name='abierta',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='caja',
            name='monto_final',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
