# Generated by Django 4.2.1 on 2023-12-18 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0056_rename_fecha_apertura_caja_fecha_hora_apertura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='abierta',
            field=models.BooleanField(),
        ),
    ]
