# Generated by Django 4.2.1 on 2023-12-19 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0057_alter_caja_abierta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caja',
            name='fecha_hora_cierre',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='monto_final',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='caja',
            name='numero',
            field=models.IntegerField(),
        ),
    ]
